export const PASSWORD_MIN_LENGTH = 6;

export const PASSWORD_INDICATOR = {
  checks: [
    {
      re: /[a-z]/,
      score: 1,
    },
    {
      re: /[A-Z]/,
      score: 5,
    },
    {
      re: /([a-z].*[A-Z])|([A-Z].*[a-z])/,
      score: 2,
    },
    {
      re: /(.*[0-9].*[0-9].*[0-9])/,
      score: 7,
    },
    {
      re: /.[!@#$%^&*?_~]/,
      score: 5,
    },
    {
      re: /(.*[!@#$%^&*?_~].*[!@#$%^&*?_~])/,
      score: 7,
    },
    {
      re: /([a-zA-Z0-9].*[!@#$%^&*?_~])|([!@#$%^&*?_~].*[a-zA-Z0-9])/,
      score: 3,
    },
    {
      re: /(.)\1+$/,
      score: 2,
    },
  ],
  options: {
    passIndex: 2,
    label: 'password.indicator.strength.label',
    verdicts: [
      'password.indicator.strength.short',
      'password.indicator.strength.very.weak',
      'password.indicator.strength.weak',
      'password.indicator.strength.good',
      'password.indicator.strength.strong',
      'password.indicator.strength.very.strong',
    ],
    colors: ['#d90c0c', '#d90c0c', '#d90c0c', '#feae3a', '#1ebc13', '#1ebc13'],
    width: ['0%', '15%', '30%', '60%', '80%', '100%'],
    scores: [10, 15, 25, 45],
    bannedPass: 'Not allowed',
    render: true,
  },
  bannedPasswords: [
    '123456',
    '12345',
    '123456789',
    'password',
    'iloveyou',
    'princess',
    'rockyou',
    '1234567',
    '12345678',
    'abc123',
    'nicole',
    'daniel',
    'babygirl',
    'monkey',
    'jessica',
    'lovely',
    'michael',
    'ashley',
    '654321',
    'qwerty',
    'password1',
    'welcome',
    'welcome1',
    'password2',
    'password01',
    'password3',
    'p@ssw0rd',
    'passw0rd',
    'password4',
    'password123',
    'summer09',
    'password6',
    'password7',
    'password9',
    'password8',
    'welcome2',
    'welcome01',
    'winter12',
    'spring2012',
    'summer12',
    'summer2012',
  ],
};
